name: Building and Deploying to CC opensource site
on: [push]
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v1
   - name: setup python version
     uses: actions/setup-python@v1
     with:
      python-version: 3.7
   - name: Install dependencies
     run: |
      pip install pipenv
      pipenv install 
      mkdir build
      pipenv run lektor build -f webpack --output-path ./build
   - name: Deploy
     uses: peaceiris/actions-gh-pages@v3
     with:
          github_token: ${{ secrets.ACCESS_TOKENS }}
          publish_dir: ./build
          publish_branch: gh-pages
